version: '3.11'

services:
  web-api:
    build: services/task_service
    volumes:
      - ./:/MatchPoint
    ports:
      - "8080:8080"
    depends_on:
      - db

  worker:
    build: services/worker
    volumes:
      - ./:/MatchPoint
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  s3:
    image: minio/minio
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: 5JVspZSmZhWNvAErGe86
      MINIO_SECRET_KEY: tWyIWjwfDMwNEaoQqqrcVU21IWwTGF4HQUvGtdsn
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    volumes:
      - ./s3data:/data